import { ISelectOptions } from '@/libs/form/components/Form/Inputs/Select/types';

export const STATES: ISelectOptions = [
  { key: 'AC', value: 'AC', label: 'AC' },
  { key: 'AL', value: 'AL', label: 'AL' },
  { key: 'AP', value: 'AP', label: 'AP' },
  { key: 'AM', value: 'AM', label: 'AM' },
  { key: 'BA', value: 'BA', label: 'BA' },
  { key: 'CE', value: 'CE', label: 'CE' },
  { key: 'DF', value: 'DF', label: 'DF' },
  { key: 'ES', value: 'ES', label: 'ES' },
  { key: 'GO', value: 'GO', label: 'GO' },
  { key: 'MA', value: 'MA', label: 'MA' },
  { key: 'MT', value: 'MT', label: 'MT' },
  { key: 'MS', value: 'MS', label: 'MS' },
  { key: 'MG', value: 'MG', label: 'MG' },
  { key: 'PA', value: 'PA', label: 'PA' },
  { key: 'PB', value: 'PB', label: 'PB' },
  { key: 'PR', value: 'PR', label: 'PR' },
  { key: 'PE', value: 'PE', label: 'PE' },
  { key: 'PI', value: 'PI', label: 'PI' },
  { key: 'RJ', value: 'RJ', label: 'RJ' },
  { key: 'RN', value: 'RN', label: 'RN' },
  { key: 'RS', value: 'RS', label: 'RS' },
  { key: 'RO', value: 'RO', label: 'RO' },
  { key: 'RR', value: 'RR', label: 'RR' },
  { key: 'SC', value: 'SC', label: 'SC' },
  { key: 'SP', value: 'SP', label: 'SP' },
  { key: 'SE', value: 'SE', label: 'SE' },
  { key: 'TO', value: 'TO', label: 'TO' },
];
